interface Props {
  report: any;
}

export function ReportExport({ report }: Props) {
  const exportMarkdown = () => {
    const md = buildMarkdown(report);
    download(`self-evo-${slug(report.query)}.md`, md, 'text/markdown');
  };

  const exportJSON = () => {
    download(`self-evo-${slug(report.query)}.json`, JSON.stringify(report, null, 2), 'application/json');
  };

  return (
    <div className="flex gap-2">
      <button onClick={exportMarkdown} className="px-3 py-1.5 bg-slate-700 hover:bg-slate-600 text-slate-300 rounded-lg text-xs transition-colors">
        Export MD
      </button>
      <button onClick={exportJSON} className="px-3 py-1.5 bg-slate-700 hover:bg-slate-600 text-slate-300 rounded-lg text-xs transition-colors">
        Export JSON
      </button>
    </div>
  );
}

function slug(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
}

function download(filename: string, content: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function buildMarkdown(report: any): string {
  const lines: string[] = [];
  lines.push(`# ${report.query}`);
  lines.push(`> Depth: ${report.depth} | Confidence: ${((report.overall_confidence || 0) * 100).toFixed(0)}% | Claims: ${(report.claims || []).length}`);
  lines.push('');

  if (report.executive_summary) {
    lines.push('## Executive Summary');
    lines.push(report.executive_summary);
    lines.push('');
  }

  if (report.findings) {
    lines.push('## Findings');
    lines.push(report.findings);
    lines.push('');
  }

  if (report.sources?.length) {
    lines.push('## Sources');
    for (const [i, s] of report.sources.entries()) {
      lines.push(`${i + 1}. [${s.title || s.url}](${s.url}) — quality: ${((s.quality || 0) * 100).toFixed(0)}%`);
    }
    lines.push('');
  }

  if (report.limitations) {
    lines.push('## Limitations');
    lines.push(report.limitations);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by Self-Evo Research Engine*');
  return lines.join('\n');
}
